# -*- coding: utf-8 -*-
"""Mainflow Task 1 Data Science with Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HAZmeoW2jApNP68a1mOTQd0iHrTpfM1O

Creating a list
"""

# Create a list, dictionary, and set
my_list = [1, 2, 3]
my_dict = {'a': 1, 'b': 2, 'c': 3}
my_set = {1, 2, 3}

# Perform operations on the list
print("Original List:", my_list)
my_list.append(4)  # Add an element to the list
print("After Adding 4 to List:", my_list)
my_list.remove(2)  # Remove an element from the list
print("After Removing 2 from List:", my_list)
my_list[1] = 10  # Modify an element in the list
print("After Modifying Index 1 to 10:", my_list)

# Perform operations on the dictionary
print("\nOriginal Dictionary:", my_dict)
my_dict['d'] = 4  # Add a key-value pair to the dictionary
print("After Adding ('d', 4):", my_dict)
del my_dict['b']  # Remove a key-value pair from the dictionary
print("After Removing Key 'b':", my_dict)
my_dict['a'] = 10  # Modify a value in the dictionary
print("After Modifying Key 'a' to 10:", my_dict)

# Perform operations on the set
print("\nOriginal Set:", my_set)
my_set.add(4)  # Add an element to the set
print("After Adding 4 to Set:", my_set)
my_set.discard(1)  # Remove an element from the set
print("After Removing 1 from Set:", my_set)