# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8yPPmkgaM_1vk8klVor5he-jOxpDdac

Loading a csv file
"""

import pandas as pd

from google.colab import drive; drive.mount('/content/drive')

data = pd.read_csv('/content/drive/MyDrive/01.Data Cleaning and Preprocessing.csv')

type(data)

data.info #concise summary

data.describe() #descriptive statistics

"""Filtering Data"""

data = data.drop_duplicates()
data

data.isnull()

data.isnull().sum()

data.notnull()

data.isnull().sum().sum()

data2= data.fillna(0)
data2

data3 = data.fillna(method='pad')
data3

"""Filling null values with the next values"""

data4 = data.fillna(method='bfill')
data4

import numpy as np
from scipy import stats

data2.columns

# Now calculate the quantiles and IQR
Q1 = data2.quantile(0.25)
Q3 = data2.quantile(0.75)
IQR = Q3 - Q1
print(IQR)

data2=data2[~((data2 < (Q1 - 1.5 * IQR)) |(data2 > (Q3 + 1.5 * IQR))).any(axis=1)]
data2

"""Calculating Summary Statistics


"""

summary_stats = data2.describe()
summary_stats

mean_value = data2.mean()
mean_value

median_value = data2.median()
median_value

std_dev = data2.std()
std_dev